services:
    snowbaha.etransactions:
        class: 'Snowbaha\EtransactionsBundle\Service\Etransactions'
        arguments:
            - '@snowbaha.etransactions.logger'
        calls:
            - ['setKey', ['%snowbaha_etransactions.env_mode%', '%snowbaha_etransactions.key_dev%', '%snowbaha_etransactions.key_prod%']]
            - ['setParameterFields', ['%snowbaha_etransactions.id%','%snowbaha_etransactions.site%', '%snowbaha_etransactions.rang%']]

    snowbaha.etransactions.twig_extension:
        class: 'Snowbaha\EtransactionsBundle\Twig\TwigExtension'
        tags:
            - { name: 'twig.extension' }

    snowbaha.etransactions.logger:
        class: 'Symfony\Bridge\Monolog\Logger'
        arguments: ['app']
        calls:
            - ['pushHandler', ['@snowbaha.etransactions.logger_handler']]

    snowbaha.etransactions.logger_handler:
        class: 'Monolog\Handler\StreamHandler'
        arguments: ['%kernel.logs_dir%/%kernel.environment%.etransaction.log', 200]
